name: CI
on:
  push:
    branches:
      - master
      - main
      - 'release*'
    tags: '*'
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ github.event_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'min'
          - '1'
          - 'nightly'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Required when authenticating with `GITHUB_TOKEN`, not needed when authenticating with SSH deploy keys
      contents: write
      pull-requests: read  # Required when using `push_preview=true`
      statuses: write  # Optional, used to report documentation build statuses
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: |
          julia --color=yes --project=docs -e '
            using Pkg
            Pkg.Registry.update()
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --color=yes --project=docs -e '
            using Documenter: DocMeta, doctest
            using DatasetManager
            DocMeta.setdocmeta!(DatasetManager, :DocTestSetup, :(using DatasetManager; include(joinpath(pkgdir(DatasetManager), "docs", "doctest-setup.jl"))); recursive=true)
            doctest(DatasetManager)'
      - run: julia --project=docs docs/extract-matlab-docstrings.jl
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
